apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-app

spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: amazon-app
    spec:
      containers:
        - name: amazon-app
          image: 997450571655.dkr.ecr.us-east-1.amazonaws.com/amazon-clone:latest
          ports:
            - containerPort: 80
