apiVersion: v1
kind: Service
metadata:
  name: amazon-app-service
spec:
  selector:
    app: amazon-app
  ports:
    - protocol: TCP
      port: 80           # External port to expose the service
      targetPort: 3000   # Port on the container
  type: LoadBalancer

